// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNOpIonpvoDi1Eo7Xe8-OA9Pf7mBor_c',
    appId: '1:450543694412:web:472efe9fca5adae12d3ae9',
    messagingSenderId: '450543694412',
    projectId: 'first-project-e0fa5',
    authDomain: 'first-project-e0fa5.firebaseapp.com',
    storageBucket: 'first-project-e0fa5.firebasestorage.app',
    measurementId: 'G-1QM6NF0BPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSsSvP7HwgQmhR54VnpSCDgJUl3Kk4DBg',
    appId: '1:450543694412:android:42f760a6221a0bde2d3ae9',
    messagingSenderId: '450543694412',
    projectId: 'first-project-e0fa5',
    storageBucket: 'first-project-e0fa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARWSwnLpDjzqqxbrGierOB3HHW14fnPNM',
    appId: '1:450543694412:ios:c7552081c962db4d2d3ae9',
    messagingSenderId: '450543694412',
    projectId: 'first-project-e0fa5',
    storageBucket: 'first-project-e0fa5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARWSwnLpDjzqqxbrGierOB3HHW14fnPNM',
    appId: '1:450543694412:ios:c7552081c962db4d2d3ae9',
    messagingSenderId: '450543694412',
    projectId: 'first-project-e0fa5',
    storageBucket: 'first-project-e0fa5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuNOpIonpvoDi1Eo7Xe8-OA9Pf7mBor_c',
    appId: '1:450543694412:web:57609eebb1a9024e2d3ae9',
    messagingSenderId: '450543694412',
    projectId: 'first-project-e0fa5',
    authDomain: 'first-project-e0fa5.firebaseapp.com',
    storageBucket: 'first-project-e0fa5.firebasestorage.app',
    measurementId: 'G-FSKBWBJBQ7',
  );
}
